<div style="width: 100%; clear: both;">
<div style="float: left; width: 50%;">
<img src="http://www.uoc.edu/portal/_resources/common/imatges/marca_UOC/UOC_Masterbrand.jpg", align="left">
</div>
</div>
<div style="float: right; width: 50%;">
<p style="margin: 0; padding-top: 22px; text-align:right;">M2.877 · Análisis de sentimientos y textos</p>
<p style="margin: 0; text-align:right;">Máster Universitario de Ciencia de Datos(Data science)</p>
<p style="margin: 0; text-align:right; padding-button: 100px;">Estudis d'Informàtica, Multimèdia i Telecomunicacions</p>
</div>
</div>
<div style="width: 100%; clear: both;">
<div style="width:100%;">&nbsp;</div>

# PRA 3: Deep Learning para el análisis de textos 

En esta práctica revisaremos y aplicaremos los conocimientos aprendidos en los módulos 5 y 6. En concreto trataremos los siguientes temas:

1. **Traducción automatica**: con custom embeddings y con embeddings preentrenados.
2. **Classificación de frases**: Aplicación de los conceptos ya trabajados para la reutilización de la arquitectura de dos modelos.

3. **Detección de NER y NEL**: detección y clasificación de entidades nombradas (NER) y entity linking basandonos en los temas ya trabajados en los notebooks de NER y NEL y añadiendo un ejemplo sencillo de transformers. 

También incluimos algunos otros temas transversales trabajados a lo largo de la asignatura.


# PARTE 1

En esta primera parte de la práctica se pide resolver los ejercicios usando la libreria **KERAS**.

# 1. Traducción Automática (4 puntos)




## 1.1 TA con Custom Embeddings (2 puntos)


El objetivo de este apartado es entrenar un modelo de traducción automática entre inglés y castellano, siguento los mismos pasos que en el notebook de Machine Translation del mòdulo 5. 


**Implementación**: Siguiendo los pasos trabajados en el notebook de traducción automática, implementar y entrenar un modelo de traducción automática, del inglés al castellano.  

+ La capa embedding debe de tener una dimensión igual a 300 
+ Se recomienda una longitud màxima de secuencia de 12
+ Se recomienda utilitzar los primeros 50000 pares del corpus de en-es.txt <br>
    
Mostrad la aplicación del modelo entrenado con algún ejemplo.

In [ ]:
!pip install numpy==1.19.5

Primero deberéis cargar los datos proporcionados, que encontraréis en el fichero mt/en-es.txt 

In [1]:
#############################################
# SOLUCIÓN                                  #
#############################################



Preprocesar los datos, para eliminar puntuaciones y poner en minúscula

In [2]:
#############################################
# SOLUCIÓN                                  #
#############################################





Visualizar los datos resultantes, para tener una idea de como van a ser los datos con los que vamos a trabajar, en concreto ver el tamaño del corpus tanto los vectores del inglés como las del castellano.

In [3]:
#############################################
# SOLUCIÓN                                  #
#############################################



In [4]:
#############################################
# SOLUCIÓN                                  #
#############################################



In [ ]:
!pip install keras

In [ ]:
!pip install tensorflow

Calcular el vocabulario tanto en castellano como en inglés, e imprimir su tamaño. 

In [5]:
#############################################
# SOLUCIÓN                                  #
#############################################





Separamos los conjuntos de entrenamiento por idioma y los codificamos. 

In [7]:
#############################################
# SOLUCIÓN                                  #
#############################################




Definimos el modelo encoder-decoder basandonos en el notebook visto en la asignatura, e instanciamos el modelo con una capa de embedding para las frases de la lengua origen (castellano) y la dimensión de la última capa como el vocabulario de la lengua destino (inglés)

In [8]:
#############################################
# SOLUCIÓN                                  #
#############################################



Compilamos el modelo

In [9]:
#############################################
# SOLUCIÓN                                  #
#############################################



Entrenamos y guardamos el modelo. 
El modelo puede tardar horas si se hace en CPU, mucho menos si se puede realizar en GPU. Colab permite el uso de GPU en general, si no se hace un uso extensivo, y se va deshabilitando la opción y habilitando segun necesidades. Si se tiene activada siempre penaliza y la desactiva. Para probar si funciona, recomendamos probar de lanzar el entrenamiento solo con una época y ver que funciona, y una vez tenemos claro que el flujo esta funcionando, ya lanzarlo con muchas más. 

Hemos visto que en Colab, a pesar de que pedimos que el tamaño de sentencia máxima sea 12, no puede cargar el modelo en memoria. Recomendamos bajarlo a 4 y el número de "units" a 200, de esta manera si que es capaz de trabajar.

In [10]:
#############################################
# SOLUCIÓN                                  #
#############################################



Una vez entrenado el modelo, se aplica con el conjunto de test para obtener unas prediciones. 

In [11]:
#############################################
# SOLUCIÓN                                  #
#############################################

Visualizamos los resultados de las predicciones con los valores esperados. Los resultados son curiosos, no podríamos usar este modelo para un entorno real como vais a poder ver. 

Pregunta: ¿Porque creéis que no son buenos, y como creéis que podrían obtenerse mejores resultados?

In [12]:
#############################################
# SOLUCIÓN                                  #
#############################################



In [13]:
#############################################
# SOLUCIÓN                                  #
#############################################



## 1.2 TA con Embeddings preentrenados (2 puntos)

En este apartado repetiremos el ejercicio anterior cargando a la capa de embedding los pesos d'un modelo GloVe entrenado para el inglés. 

Empezamos cargando el modelo GloVe para el inglés. Podéis usar 'glove.42B.300d.txt'.

In [ ]:
# Podemos cargar el fichero glove desde Google Drive
from google.colab import drive
drive.mount('/gdrive', force_remount=True)

from pathlib import Path
%cd /gdrive/My Drive/Temporal
print (f"Current working directory: {Path.cwd()}")

Mounted at /gdrive
/gdrive/My Drive/Temporal
Current working directory: /gdrive/My Drive/Temporal


In [ ]:
import numpy as np

embeddings_index = {}
f = open('glove.42B.300d.txt')
for line in f:
    values = line.split()
    word = values[0]
    coefs = np.asarray(values[1:], dtype='float32')
    embeddings_index[word] = coefs
f.close()

print(len(embeddings_index))

1917494


A continuación, tenemos que contruir la matriz de embeddings. 
Para no cargar todo el vocabulario del modelo, podemos filtrar solo aquellas entradas presentes en el vocabulario del tokenizador que usaremos. Además, tenemos de incluir en la matriz de vectores correspondientes los índices de las entradas (palabras) que no encontremos en el modelo glove cargado. Estos vectores se suelen inicializar con 0s o con el resultado de una distribución N(0,1)

Por ejemplo, si nuestro tokenizador se llamara `eng_tokenizer` podríamos hacer:

In [ ]:
embedding_matrix = np.zeros((len(eng_tokenizer.word_index) + 1, 300))
for word, i in eng_tokenizer.word_index.items():
    embedding_vector = embeddings_index.get(word)
    if embedding_vector is not None:
        embedding_matrix[i] = embedding_vector


Para inicializar una capa de embeddings con pesos predefinidos se utiliza el argumento `weights`. Además, como no queremos que se modifiquen los pesos, marcamos el argumento `trainable` como `False`. 

Siguiendo con nuestro ejemplo, haríamos:

In [ ]:
from keras.layers import Embedding

embedding_layer = Embedding(len(eng_tokenizer.word_index) + 1,
                            embedding_vec_length,
                            weights=[embedding_matrix],
                            input_length=max_text_length,
                            trainable=False,
                            mask_zero=True)


Implementa y entrena de nuevo un modelo de traducción automática del inglés al castellano de forma similar, esta vez cargando los pesos de la capa embedding a partir del modelo Glove preentrenado en inglés y disponible en 'glove.42B.300d.txt'.


In [14]:
#############################################
# SOLUCIÓN                                  #
#############################################



Entrenamos y guardamos el modelo. Otra vez, aunque este entrenamiento es quizá un "poco" más liviano que el anterior, recomendamos el uso de GPU si es viable.

In [16]:
#############################################
# SOLUCIÓN                                  #
#############################################




Aplicar el modelo y visualizar los resultados a partir de las prediciones obtenidas con este nuevo modelo.

In [17]:
#############################################
# SOLUCIÓN                                  #
#############################################



<div style="background-color: #EDF7FF; border-color: #7C9DBF; border-left: 5px solid #7C9DBF; padding: 0.5em;">
<strong>(Opcional) Análisis:</strong> Explica cuales són las principales diferencias entre los dos modelos entrenados. ¿Como podríamos mejorar los resultados de esta tarea en concreto?
</div>

# PARTE 2


# 2. Classificación de frases (3 puntos)

En este apartado planteamos el uso de las arquitecturas vistas hasta el momento para crear un clasificador de notícias en inglés. 
En concreto usaremos este dataset:
https://www.kaggle.com/datasets/amananandrai/ag-news-classification-dataset/code
Que clasifica les notícas en 4 tipos, "world", "sports", "business", y "Science"

Lo que haremos primero será obtener el conjunto de datos de entrenamiento, cargarlo en un dataframe de pandas, seleccionar las columnas "Title" y "Class Index" y almacenar sus datos con el formato que utilizaremos para entrenar, 2 listas, la "data" y la "data_labels".

En concreto las listas:

1. **data**, contendrá todos los títulos de las noticias
2. **data_labels**, todas las etiquetas.


Ambas listas deben tener el mismo *tamaño*, ya que por un lado están las noticias, y cada noticia tiene una etiqueta.

Se puede samplear el corpus y coger sólo las **10000** primeras entradas para que el script vaya más rápido. Más adelante podremos realizar pruebas para ver si añadiendo más entradas tenemos mejores resultados.

In [ ]:

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)


train=pd.read_csv('class/train.csv')

train_sample=train.sample(n=10000)
title=train_sample['Title'].tolist()
tag=train_sample['Class Index'].tolist()

print (len(title))
print (len(tag))

data=[]
data_labels=[]
for i in range (0, len(title)):
    data.append(title[i])
    data_labels.append(tag[i])

10000
10000


Visualizad la distribución de textos por clase.


In [18]:
#############################################
# SOLUCIÓN                                  #
#############################################




Preparad y preprocesad los datos para el entrenamiento. Utilizaremos one-hot encoding por las etiquetas.

In [ ]:
!pip install sklearn

In [ ]:


from numpy import array
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

values = array(data_labels)
print(values)

label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print(integer_encoded)

onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)


[1 2 2 ... 2 4 1]
[0 1 1 ... 1 3 0]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 ...
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]]


## 2.1 Preparar datos y embeddings para entrenar (1 punto)
La idea del modelo de clasificación que queremos implementar es más simple que la del encoder-decoder usado en el apartado 1.

El modelo debe consistir sólo en:

- una capa embedding con los pesos del modelo Glove preentrenado para el inglés disponible en el archivo 'glove.42B.300d.txt'
- una capa LSTM con un número de units a elegir (por ejemplo, 300)
- una capa Dense con una dimensión de salida que tiene el número de categorías con las que queremos clasificar (en este caso, 4).
- Además, como loss function `loss` utilizaremos 'categorical_crossentropy' y como `optimizer`, 'adam'.

Primeramente creamos un tokenizador para las frases del clasificador

In [19]:
#############################################
# SOLUCIÓN                               #
#############################################




Cargamos el siguiente modelo GloVe para el inglés. Lo hemos utilizado en la parte 1.

In [20]:
#############################################
# SOLUCIÓN                                #
#############################################


Una vez cargado el modelo de GloVe definimos la capa de Embedding con todos sus pesos


In [21]:
#############################################
# SOLUCIÓN                                  #
#############################################



Preparamos el corpus de entrenamiento y test, usando el model_selection de sklearn, y el onehot_encoded para las clases. Usamos 80% para train. 

In [22]:
#############################################
# SOLUCIÓN                                  #
#############################################



Codificar los vectores de entrada para el train y para el text

In [23]:
#############################################
# SOLUCIÓN                                  #
#############################################




## 2.2 Definir el modelo y entrenar (1 punto).

El modelo debe consistir sólo en:

+ una capa embedding con los pesos del modelo Glove preentrenado para el inglés disponible en el archivo 'glove.42B.300d.txt'
+ una capa LSTM con un número de units a elegir (por ejemplo, 300)
+ una capa Dense con una dimensión de salida que tiene el número de categorías con las que queremos clasificar (en este caso, 4).

Además, como loss function utilizaremos 'categorical_crossentropy' y como optimizer, 'adam'.

In [24]:
#############################################
# SOLUCIÓN                                  #
#############################################



Compilar el modelo

In [25]:
#############################################
# SOLUCIÓN                                  #
#############################################



Entrenar y guardar el modelo. En esta sección aunque sea recomendable usar GPU, con CPU también se puede obtener el resultado sin tener que esperar "mucho" tiempo

In [26]:
#############################################
# SOLUCIÓN                                  #
#############################################




## 2.3 Evaluar el modelo (1 punto)
Se evalua el modelo y se obtienen sus diferentes métricas. 

In [27]:
#############################################
# SOLUCIÓN                                  #
#############################################



¿Que pasaría si el modelo de clasificación lo entrenaramos con más datos?
¿Y si no usaramos los embeddings de Glove? ¿Que nos aportan ambas cosas?
¿Si usamos más datos hacen falta usar los embeddings?

Expresar vuestra opinión con una mínima experimentación para obtener las conclusiones.



# PARTE 3



# 3. Detección de NER (3 puntos)

En esta parte intentaremos entrenar y detectar entidades nombradas utilizando tanto SpaCy con transformers como transformers simplemente usando una librería llamada simple transformers.

Por otro lado, también haremos Named Entity Linking (NEL) donde buscaremos entidades linkadas a una base de conocimiento (KB), en este caso DBpedia. Encontraremos los enlaces a Wikpedia de ciertas entidades del texto, utilizando DBPedia Spotlight.

## 3.1 Detección de NER con spaCy (2 puntos)

En esta sección usaremos spaCy para detectar NER. A partir de un corpus de CONLL 2003, lo reeentrenaremos y de esta manera afinaremos su cobertura para estas clases. 

Instalamos spacy y mos modelos de lenguaje que necesitemos. 

In [ ]:
!pip install spacy==3.2.0

!python -m spacy download en_core_web_sm-3.2.0 --direct

Definimos un par de funciones que nos va a permitir imprimir los resultados de la detección de NER de forma muy interpretable

In [ ]:
def get_tokens_to_print(model, text):
  """Print tokens of the text and its relevant attributes.

    Parameters:
      model (spaCy model): spaCy model used for tokenization
      text (str):  text to transform in a spaCy doc class.

    Returns: ---
  """
  doc = model(text)
  print (f"The text:\n\n{get_text_to_print(text)}\n\nwas converted in a spaCy object: {type(doc)}\n")
  print (f"Token-based analysis. Each token is a spaCy object: {type(doc[0])}\n")
  
  # Obtener las filas para imprimir
  rows  = []
  # head_align: Lista de tuplas. Cada tupla: Cabecera de la columna y su alineación al imprimir
  head_align  = [('Token', '<'), ('Lemma', '<'), ('Syntactic parent', '<'), ('#Tok', '>'), ('Chr_Start', '>'), ('Chr_End', '>'), ('POS', '<'), 
                 ('TAG', '<'), ('TAG meaning:', '<'), ('ENT', '<'), ('DEP', '<'), ('DEP meaning:', '<')]   
  head, align = list(zip(*head_align))  
  rows.append(head)                           
  rows.append(['='*len(i) for i in head])     
  for tok in doc:
    rows.append([tok.text, tok.lemma_, tok.head.text, str(tok.i), str(tok.idx), str(tok.idx+len(tok)-1), tok.pos_, 
                 tok.tag_, str(spacy.explain(tok.tag_))[:20], tok.ent_type_, tok.dep_, str(spacy.explain(tok.dep_))[:20]])
  
  # Ancho de cada columna: igual al elemento más ancho de la columna
  columns       = zip(*rows)     
  column_widths = [max(len(i) for i in col) for col in columns]

  # Imprimir 
  for row in rows:
    print(*[f"{row[i]:{align[i]}{column_widths[i]}}  " for i in range(0, len(row))])

In [ ]:
def get_text_to_print(text):
  """Format given text.

    Parameters:
      text (str): text to print

    Returns:
      str: text formatted in 100 character lines with an initial line numbering the characters
  """
  line_length = 100
  line_poss   = "     1-------10--------20--------30--------40--------50--------60--------70--------80--------90-------100"
  text        = text.replace("\n", " ")     
  text        = text.replace("\r", " ")     
  text_format = "\n".join([ f"{i//line_length:<5}{text[i:i+line_length]}"  for i in range(0, len(text), line_length) ])
  return line_poss + "\n" + text_format + "\n" + line_poss

Cargamos el modelo "en_core_web_sm"

In [28]:
##################
## SOLUCION ####
##################



Convertimos un texto en objecto 'Doc' de spaCy y visualizamos los resultados de analizar este texto a nivel de POS, NER, ENT, DEP... 

In [29]:
##################
## SOLUCION ####
##################




Entrenar un nuevo modelo de NER con los datos de CONLL2003

Convertimos los ficheros conll03 (train y valid) a formato spaCy. 
El corpus lo hemos obtenido de aquí:
https://github.com/Hironsan/anago

Nota: spacy contiene funciones que permiten convertir de formato conll al formato compilado que necesitan el módulo de train de spaCy. 


In [30]:
#####################
### SOLUCION ###
##################


Descargar el modelo 'en_core_web_trf'

In [ ]:
!python -m spacy download en_core_web_trf

In [ ]:
!python -m spacy validate

In [ ]:
import spacy
print (f"Spacy version installed: {spacy.__version__}")

Spacy version installed: 3.2.0


Entrenar usando la función train de spaCy a partir del modelo 'en_core_web_trf'. 
Usar el fichero de configuración adjunto y modificar las cosas que consideréis oportundas. La versión entregada ya funciona pero se puede customizar si hay interés. 

In [31]:
##################
### SOLUCION ###
################



Predecir una frase de ejemplo con el nuevo modelo y visualizar los resultados. 
Ojo que colab, no le gusta cargar modelos desde paths, solo si estan en local. con lo que recomendamos, generar el modelo en drive, guardarlo y luego subir la mejor versión para cargarlo desde de aquí. 


In [ ]:
##################
### SOLUCION ###
################


Evaluar los resultados obtenidos y calcular las métricas

In [32]:
############ 
###SOLUCION##
##############



## 3.2 Detección y entrenamiento de NER con Simple Transformers (0.5 punto)

Probaremos de entrenar un modelo también haciendo uso de Transformers para la detección de NER pero sin usar SPACY. 
En este caso, usaremos Simple Transformers, la documentación está aquí:

https://simpletransformers.ai/docs/ner-model/

Es una manera de generar modelos sencilla. 

En primera instancia prepararemos el dataset que utilizaremos. Utilizaremos el CONLL2003.
El corpus lo hemos obtenido de aquí:
https://github.com/Hironsan/anago

El dataset debe estar como una lista de listas. Donde cada lista contiene el número de la frase, el token y si es NER o no en el formato BIO.

In [ ]:
def create_dataset(dataset):
    f = open(dataset, "r")
    num_sentence=0

    doc=[]
    for i in f:

        frase=i.strip()
  
        if (num_sentence < 1500):
            if len(frase)==0:
                num_sentence=num_sentence+1

            else:
                #print ("no empty", frase)
                dos=frase.split("\t")

                if (len(dos)==2):
                    #print (sentence, dos[0], dos[1])
                    l=[num_sentence, dos[0],dos[1]]
                    doc.append(l)
    print (num_sentence)            
    return doc

train_data=create_dataset("ner/conll03/train.txt")
eval_data=create_dataset("ner/conll03/test.txt")
print (eval_data)
print (len(eval_data))

Convertiremos el dataset con las mismas columnas que hay en los archivos de train/test a un dataframe de Pandas. Donde está el identificador de la frase, palabra, etiqueta.

In [33]:
############################
##### SOLUCION #####
########################



Importamos el paquete simple transformers y creamos un modelo NER, basado en bert, y con los siguientes parámetros como argumentos:
"overwrite_output_dir": True
"reprocess_input_data": True

Le decimos que no use GPU (use_cuda=False) en caso de no tener disponible. En caso de tener GPU disponible podemos indicar use_cuda=True


In [34]:
################################
####### SOLUCION #######
##################################





Entrenamos el modelo

In [35]:
################################
####### SOLUCION #######
##################################


Evaluamos el modelo

In [36]:
################################
####### SOLUCION #######
##################################





Imprimimos los resultados y vemos algun ejemplo para ver que pinta tiene el uso de este modelo

In [37]:
################################
####### SOLUCION #######
##################################


Que diferencias claras ves entre este modelo y el modelo anterior donde se ha usado SPACY? 

## 3.3 NEL (0.5 punto)

En esta sección, la idea es obtener los enlaces en la DBpedia spotlight relacionados con las entidades que se han obtenido de NER usando SPACY. 






Desarrolla una función que dado un texto, te obtenga automáticamente las entidades relacionadas en el DBpedia Spotlight.

URL de acceso a la API, DBPedia inglés: https://www.dbpedia-spotlight.org/api o https://www.dbpedia-spotlight.org/api/en  

In [38]:
##############################
# SOLUCIÓN #
########################



Prepara una función que a acceda a la función desarrollada anteriormente y analize un texto, teniendo en cuenta que se pueden configurar estos parametros:


+ confidence (float): score de confianza para la desambiguación
+ support (int): relevancia de la entidad, basada en los links de Wikipedia
+ dbpedia_lan (str): idioma de la wikipedia
+ list_types (list): listado de tipos que se van a filtar de acuerdo con la ontologia de la dbpedia(rdf:type). La lista puede ser vacía.
+ base_url: url DBPedia Spotlight API
+ action: acción definida en la API de la DBpedia (anotar, spot, candidates)

Todos estos parametros son parametros que coge la API de DBpedia, no hay que hacer ningún calculo especial, simplemente añadir la opción de poder jugar con ellos. 


In [ ]:
##############################
# SOLUCIO #
########################



In [ ]:
!pip install requests

A partir de un texto de ejemplo, calcular los enlaces de DBpedia y visualizarlos. 

In [39]:
##############################
# SOLUCIÓN #
########################
